% Function to return the result to be integrated to find the generated
% current

function ret = calculate_spectrum_int(x, L, S, D, W, spectrums)
    ret = (cosh(x / L) - ...
        (((((S * L / D) * cosh(W / L)) + sinh(W / L)) ...
        / (((S * L / D) * sinh(W / L)) + cosh(W / L))) ...
        * sinh(x / L))) ...
        * exp(-1 * spectrums.Si(:,1) * x);
end