function F = evaluate_si_Voc(v, par, res)
    F = ((v - res.Vbi2) / par.VT) + log(abs((res.Jdiffd2 + res.Jradd2) ...
        + (res.Jscrd2 * exp(-(v - res.Vbi2)/(2 * par.VT))))) ...
        - log(abs(res.Jillum2 - (v / (par.A * par.Rsh2))));
end