function F = evaluate_si_Voc(v, params, res)
    F = ((v - res.Vbi2) / params.VT) + log(abs((res.Jdiffd2 + res.Jradd2) ...
        + (res.Jscrd2 * exp(-(v - res.Vbi2)/(2 * params.VT))))) ...
        - log(abs(res.Jillum2 - (v / (params.A * params.Rsh2))));
end