function F = evaluate_single_ideal(j, V, params)
    F = (((V - params.Vbi)/params.VT) * log(abs((params.Jdiffd + params.Jradd) ...
        + params.Jscrd * exp(-(V - params.Vbi)/(2*params.VT))))) ...
        - log(params.Jillum - j);
end