function F = evaluate_single_ideal_Voc(v, params)
    F = ((v - params.Vbi) / params.VT) + log(abs((params.Jdiffd + params.Jradd) ...
        + (params.Jscrd * exp(-(v - params.Vbi)/(2 * params.VT))))) ...
        - log(params.Jillum);
end