% Current density - Voltage Plot

function fig = J_V(res, setting)
    % Clear data from the figure if already open
    clf(figure(1));

    % Set the axes numbers font sizes
    set(groot, 'defaultAxesFontSize', setting.axes_numbers);

    % Plot in figure 1
    fig = figure(1);
    tiledlayout(1, 3);

    % Plot the total cell J-V curve
    ax1 = nexttile;
    plot(res.V, res.J, 'LineWidth', setting.line_width);
    xline(0);
    yline(0);
    if setting.title
        title('PVK-Si Tandem Cell Current Density - Voltage', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    else
        title('Total PVK-Si Tandem Cell', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    end
    xlabel('Bias Voltage (V)', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);
    ylabel('Current Density $\left(\mathrm{mA~cm}^{-2}\right)$', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);

    % Plot cell 1's J-V curve
    ax2 = nexttile;
    plot(res.V1T, res.J, 'LineWidth', setting.line_width);
    xline(0);
    yline(0);
    if setting.title
        title('PVK J-V', 'Interpreter', 'latex', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    else
        title('PVK', 'Interpreter', 'latex', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    end
    xlabel('PVK Voltage (V)', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);
    ylabel('PVK Current Density $\left(\mathrm{mA~cm}^{-2}\right)$', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);

    % Plot cell 2's J-V curve
    ax3 = nexttile;
    plot(res.V2T, res.J, 'LineWidth', setting.line_width);
    xline(0);
    yline(0);
    if setting.title
        title('Silicon J-V', 'Interpreter', 'latex', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    else
        title('Silicon', 'Interpreter', 'latex', ...
            'Interpreter', 'latex', ...
            'FontSize', setting.title_font);
    end
    xlabel('Silicon Voltage (V)', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);
    ylabel('Silicon Current Density $\left(\mathrm{mA~cm}^{-2}\right)$', ...
        'Interpreter', 'latex', ...
        'FontSize', setting.axes_font);

    % Set the y-axis to the same for all three plots
    linkaxes([ax1 ax2 ax3], 'y');
end